### ISSUE TITLE
Fix 500 error on /api/FileSystems/{account}/{container} endpoint

### ISSUE THREAD

**Issue by johnbradley** [microsoft/storage-as-a-service#111]
When a bogus storage account name is used the API hangs for a while and then returns a 500 error.
To reproduce using our deployment of storage-as-a-serivce set KEY to be your API key and run:
```
$ curl -v -H "Saas-FileSystems-Api-Key: $KEY" https://azurestorage.duhs.duke.edu/api/FileSystems/badaccountname/containername
```

Thanks.

**Comment by johnbradley** [comment]
@SvenAelterman Here is the issue I created for the 500 error when the storage account isn't found.

**Comment by SvenAelterman** [comment]
@johnbradley Thank you for reporting this issue. PR #130 is pending review.
