### ISSUE TITLE
Copyright not properly adjusting to page size

### ISSUE THREAD

**Issue by mickdigrazia** [microsoft/storage-as-a-service#35]
Copyright content is overlapping table with fileshare content. If browser window is resized, copyright floats upward

![copyright](https://user-images.githubusercontent.com/95648469/155007705-44dfd264-b30c-466a-961e-7819a65cb47e.jpg)

**Comment by SvenAelterman** [comment]
@mickdigrazia Thanks for reporting. I am looking into it.

**Comment by SvenAelterman** [comment]
@mickdigrazia I believe this issue has been addressed pending review of pull request #54

**Comment by mickdigrazia** [comment]
> @mickdigrazia I believe this issue has been addressed pending review of pull request #54

Great! Thanks @SvenAelterman
