### ISSUE TITLE
New Folder Creation not working

### ISSUE THREAD

**Issue by mickdigrazia** [microsoft/storage-as-a-service#37]
Using latest version, upon using Create New Folder function, message "Folder 'undefined' Created!" appears with no folder created
![newfolder](https://user-images.githubusercontent.com/95648469/155177706-fac42b2b-8cd3-4ff1-9890-07ed1a573dbd.jpg)

**Comment by SvenAelterman** [comment]
@mickdigrazia Thanks for sharing the screenshot. I think I've seen this behavior before. I am reviewing my chat logs to see waht the resolution was.

**Comment by softcraftsman** [comment]
I fixed this with the builds from last night.  Didn't realize there was an open issue to attach.
