### ISSUE TITLE
Storage Explorer deep links

### ISSUE THREAD

**Issue by softcraftsman** [microsoft/storage-as-a-service#71]
Add a link to the connection page that allows for Storage Explorer deep links.

storageexplorer://v=1&accountid=/subscriptions/the_subscription_id/resourceGroups/the_resource_group_name/providers/Microsoft.Storage/storageAccounts/the_storage_account_name&subscriptionid=the_subscription_id&resourcetype=Azure.BlobContainer&resourcename=the_blob_container_name

**Comment by SvenAelterman** [comment]
MS Doc: https://docs.microsoft.com/en-us/azure/storage/common/storage-explorer-direct-link
